<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_</name>
   <tag></tag>
   <elementGuidId>7b71719a-6f8c-4bcc-b33c-55c74a6476a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value> //body/div[contains(@class, 'contentPanel')]/div[contains(@class, 'x-panel-body')]/div[not(contains(@style,'display: none')) and contains(@class,x-panel)]//tr[contains(@role,'row')][1]
</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.x-grid-row-checker</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1b561fa3-06c8-4777-8b43-158d6d14de86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-grid-row-checker</value>
      <webElementGuid>1819bd3d-8b7d-4dd9-8eaa-104b24162871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>9a45782a-5bb0-43c2-b998-7e4e34712d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ext-gen4443&quot;)/div[@class=&quot;x-grid-cell-inner&quot;]/div[@class=&quot;x-grid-row-checker&quot;]</value>
      <webElementGuid>2d0bf4ee-6708-4515-8cb9-ab69b1d4c3dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='ext-gen4443']/div/div</value>
      <webElementGuid>ca31970a-42c8-4d68-bffc-3945ca3f738f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enrollment Status123'])[1]/following::div[5]</value>
      <webElementGuid>501e7a67-94e2-475a-aaa5-c786822eb61e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fee Payer'])[1]/following::div[8]</value>
      <webElementGuid>26fd534d-040a-4076-b9b1-f3ee46d753b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AP10004505'])[1]/preceding::div[1]</value>
      <webElementGuid>ee0f6bf0-52a2-474d-96e4-abc9c9decf0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AD10002833'])[1]/preceding::div[2]</value>
      <webElementGuid>41fa8c2f-5669-400a-8de4-1000ed383866</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/table/tbody/tr/td/div/div</value>
      <webElementGuid>be69250e-9611-4788-a05f-f0db768ba302</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' ' or . = ' ')]</value>
      <webElementGuid>5424b22f-b237-48c1-b57d-4a025bbc030a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
