<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Students List_button-1194-btnIconEl</name>
   <tag></tag>
   <elementGuidId>a0d0face-b878-4b21-8d2a-1a9d29f05a9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='button-1194-btnIconEl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#button-1194-btnIconEl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>842c83e6-8e00-4ec3-ae7f-14605db208b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>fc0af12d-beee-4914-8f17-8356883ee418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-1194-btnIconEl</value>
      <webElementGuid>3918ca82-f2eb-400f-aaaf-62499a29dbcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-icon-el  </value>
      <webElementGuid>d2b56e32-004d-4899-b236-571a3667f8f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>d6e758a8-6ea9-4f88-ac70-70998753c056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-1194-btnIconEl&quot;)</value>
      <webElementGuid>55d0efd3-7f1f-45d1-be27-239545fd38cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='button-1194-btnIconEl']</value>
      <webElementGuid>5d799044-0184-4b4c-ac25-b21424396850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='button-1194-btnEl']/span[2]</value>
      <webElementGuid>9317b66a-ae16-4365-a1e9-ada57b7c3ff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[33]/div/div[2]/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/a/span/span/span[2]</value>
      <webElementGuid>4f1714ab-3ea4-4a03-8996-dea907a5987c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'button-1194-btnIconEl']</value>
      <webElementGuid>192d9a7e-fe75-48c8-8e19-19b309cd4096</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
