<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Students</name>
   <tag></tag>
   <elementGuidId>cd98c6be-94a7-485f-9236-67134a3f67f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='verticalnavigationmenubutton-1188-btnWrap']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#verticalnavigationmenubutton-1188-btnWrap</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>24bfa5a0-6f67-4237-a567-dfccf5757970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>verticalnavigationmenubutton-1188-btnWrap</value>
      <webElementGuid>111d01b0-4070-49a6-852e-cb0dd5fae550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-wrap x-btn-arrow x-btn-arrow-right</value>
      <webElementGuid>909c9865-5bb0-4a44-a3af-db84774b8875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>75f4c948-5585-4ee6-984a-89193e2adb29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Students </value>
      <webElementGuid>c50a7d1f-8781-4c37-8fee-a5c3270f431f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;verticalnavigationmenubutton-1188-btnWrap&quot;)</value>
      <webElementGuid>dcb14ea5-546f-4d57-a42c-484527469dbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='verticalnavigationmenubutton-1188-btnWrap']</value>
      <webElementGuid>63a95020-a588-4e09-b061-f53e24909f67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='verticalnavigationmenubutton-1188']/span</value>
      <webElementGuid>e4455892-e2ce-47a2-9c1e-1addcd7b8193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admissions'])[1]/following::span[2]</value>
      <webElementGuid>561a7911-8047-4f85-935f-fcca4c5b067a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pre-Admissions'])[1]/following::span[6]</value>
      <webElementGuid>b810877a-6c7c-4484-a6e6-c00053a5ed9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grades &amp; Subjects'])[1]/preceding::span[4]</value>
      <webElementGuid>245b33c8-0ab2-4136-932b-b837ed363715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/span</value>
      <webElementGuid>74b73d5c-ab86-4703-b556-d4377b6d23a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'verticalnavigationmenubutton-1188-btnWrap' and (text() = 'Students ' or . = 'Students ')]</value>
      <webElementGuid>6ece2f72-ff5e-454f-b584-7ef29ce8aa8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
