<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Search_button-2393-btnIconEl</name>
   <tag></tag>
   <elementGuidId>4d99ebde-e655-4afe-ad27-ed05d6ed0d26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='button-2393-btnIconEl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#button-2393-btnIconEl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bd79451a-d220-4659-9964-d4ae63f08da8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>fe198598-c47a-4887-a8bf-6cb26a16dd39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-2393-btnIconEl</value>
      <webElementGuid>4f0e1ff0-813d-4527-9829-2096dc7996a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-icon-el  </value>
      <webElementGuid>b091f4e1-63b6-4180-9a38-37cd9406b2e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>7b5e4978-0c11-42db-bb36-4752a5535b3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-2393-btnIconEl&quot;)</value>
      <webElementGuid>44146a8f-6be0-4428-bb9a-37a05a8c8c7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='button-2393-btnIconEl']</value>
      <webElementGuid>21e7f801-efaf-4e37-b7f1-ea7fcc585a4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='button-2393-btnEl']/span[2]</value>
      <webElementGuid>f703dfbc-ce53-4d7c-bb7c-776974aad337</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/a/span/span/span[2]</value>
      <webElementGuid>083c7b1b-a2d0-45a8-97c6-74331facd512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'button-2393-btnIconEl']</value>
      <webElementGuid>61839968-21f9-4909-a9e1-521fd2498568</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
