<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>intake</name>
   <tag></tag>
   <elementGuidId>0f3aa75c-2cdd-4bb1-93f8-74e6d44af9fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>input[name='batchId']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
