<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Administrator</name>
   <tag></tag>
   <elementGuidId>638c517a-c4db-4571-88d7-77c89c1474ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[contains(text() , 'Administrator')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#label-1041</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>19f2e462-1723-44b6-a535-e2fb320c317a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-component portal-name x-box-item x-component-default</value>
      <webElementGuid>5a42f02a-169d-45ec-868b-de5d072b1b76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>label-1041</value>
      <webElementGuid>32b1c883-33f7-476c-9beb-8a0db52d57aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Administrator</value>
      <webElementGuid>d6b1eb63-cb73-4de5-ba60-6ea96440e679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;label-1041&quot;)</value>
      <webElementGuid>68d6e1bb-f54f-4f70-a394-5bf44acb6f86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='label-1041']</value>
      <webElementGuid>cf17fc89-f3a7-45b7-9e6a-662698a909ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='portaldetails-1039-targetEl']/label</value>
      <webElementGuid>050418c7-c43c-45ee-90c3-d753b0730c27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Crawford International Lonehill'])[1]/following::label[1]</value>
      <webElementGuid>72fb97df-bf40-4bda-bc72-fb29ffe5fafe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SystXm XdmXnXstrXtXr'])[1]/preceding::label[1]</value>
      <webElementGuid>f8887250-8881-4a04-9358-82347e5cd38a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brand Campus:'])[1]/preceding::label[2]</value>
      <webElementGuid>118f1d5f-dc0c-4541-950f-01379ff9f071</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Administrator']/parent::*</value>
      <webElementGuid>4e0caf22-556d-4b47-afc5-ae5eb68cf2ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>fc1b6e57-270a-4faf-b8f6-e3309a9aeaf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'label-1041' and (text() = 'Administrator' or . = 'Administrator')]</value>
      <webElementGuid>ea517cfc-79fe-48f8-96b3-814cab11ec34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
